import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

import { NavModalProvider } from "./_components/NavModalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} dark:bg-sky-900 antialiased mx-auto`}
      >
        <NavModalProvider>
          <Header />
        </NavModalProvider>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
